name: Check-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.3.1
    - uses: ashutoshvarma/setup-ninja@v1
    - name: Meson Build
      uses: BSFishy/meson-build@v1.0.1
      with:
        action: build
        meson-version: 0.49.2
