name: Check-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/github-script@v2.0.0
      name: Setup environment
      with:
        script: |
          apt update && \
          apt install meson valac-bin libgtk3-dev libsoup2.4-dev libgranite-dev libjson-glib-dev -y;
