name: Check-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:elementary-os/stable && \
        sudo apt-get update && \
        sudo apt-get install meson valac libgtk-3-dev libsoup2.4-dev libgranite-dev libjson-glib-dev -y;
    - name: Build project
      run: meson build && ninja -C build
